{
    "osv": {
        "package": {
            "name": "python-django"
        },
        "published": "2018-04-01",
        "references": [
            {
                "type": "DSA",
                "url": "https://www.debian.org/security/2018/dsa-4161"
            }
        ]
    },
    "uvi": {
        "experimental": {
            "advisory_type": "DSA-4161-1",
            "other_identifiers": {
                "cve": [
                    "CVE-2018-7536",
                    "CVE-2018-7537"
                ]
            },
            "package_affected": [
                {
                    "distribution_affected": "jessie",
                    "fixed in": "1.7.11-1+deb8u3"
                },
                {
                    "distribution_affected": "stretch",
                    "fixed in": "1:1.10.7-2+deb9u1"
                }
            ],
            "package_name": "python-django",
            "processed_timestamp": "2021-07-18T03:09:13.623743Z",
            "uvi_script_name": "./www.debian.org-processing.py",
            "uvi_script_version": "0.0.5",
            "vulnerability_status": "yes"
        },
        "product_name": "Linux",
        "vendor_name": "Debian"
    }
}