{
    "error": "HTTPSConnectionPool(host='breaking.technology', port=443): Max retries exceeded with url: /advisories/CVE-2014-3830.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f52db0d2cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
}