{
    "error": "HTTPConnectionPool(host='apache-ignite-developers.2346864.n4.nabble.com', port=80): Max retries exceeded with url: /CVE-2014-0114-Apache-Ignite-is-vulnerable-to-existing-CVE-2014-0114-td31205.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7effc5aa1c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
}