{
    "error": "HTTPConnectionPool(host='activemq.2283324.n4.nabble.com', port=80): Max retries exceeded with url: /About-CVE-2014-3576-tp4699628.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7effc5c05a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
}