{
    "osv": {
        "package": {
            "name": "python-django"
        },
        "published": "2015-07-08",
        "references": [
            {
                "type": "DSA",
                "url": "https://www.debian.org/security/2015/dsa-3305"
            }
        ]
    },
    "uvi": {
        "experimental": {
            "advisory_type": "DSA-3305-1",
            "other_identifiers": {
                "cve": [
                    "CVE-2015-5144",
                    "CVE-2015-5143"
                ]
            },
            "package_affected": [
                {
                    "distribution_affected": "wheezy",
                    "fixed in": "1.4.5-1+deb7u12"
                },
                {
                    "distribution_affected": "jessie",
                    "fixed in": "1.7.7-1+deb8u1"
                },
                {
                    "distribution_affected": "sid",
                    "fixed in": "For the unstable distribution (sid), these problems will be fixed soon"
                }
            ],
            "package_name": "python-django",
            "processed_timestamp": "2021-07-18T03:09:01.528390Z",
            "uvi_script_name": "./www.debian.org-processing.py",
            "uvi_script_version": "0.0.5",
            "vulnerability_status": "yes"
        },
        "product_name": "Linux",
        "vendor_name": "Debian"
    }
}