{
    "uvi": [
        {
            "extracted_data": [
                {
                    "advisory_id": "DSA-3305-1",
                    "advisory_type": "DSA",
                    "affected": [
                        {
                            "distribution_affected": "wheezy",
                            "fixed in": "1.4.5-1+deb7u12"
                        },
                        {
                            "distribution_affected": "jessie",
                            "fixed in": "1.7.7-1+deb8u1"
                        },
                        {
                            "distribution_affected": "sid",
                            "fixed in": "For the unstable distribution (sid), these problems will be fixed soon"
                        }
                    ],
                    "cve_ids": [
                        "CVE-2015-5143",
                        "CVE-2015-5144"
                    ],
                    "info_date_string": "2015-07-08",
                    "package_name": "python-django",
                    "product_name": "Linux",
                    "vendor_name": "Debian",
                    "vulnerability_status": "yes"
                }
            ],
            "meta_data": {
                "uvi_processed_timestamp": "2021-08-02T18:00:45.284967Z",
                "uvi_script_hash": "ca9172205e7c7a381f3890860aa74e48712d5d43dcb3def3f146c102d9768c000a57bea2378f72674978670f0b1a3a9df8aa4ee26d64f2bb8420bf0cd86d2f48",
                "uvi_script_name": "./www.debian.org-processing.py",
                "uvi_script_version": "0.1.0",
                "uvi_url_processed": "https://www.debian.org/security/2015/dsa-3305"
            }
        }
    ]
}