<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head>
<link rel="icon" href="/favicon.png">
<title>#854442 - XXE vulnerability in python-openpyxl - Debian Bug report logs</title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/css/bugs.css" type="text/css">

<link rel="canonical" href="&lt;a href=&quot;bugreport.cgi?bug=854442&quot;&gt;854442&lt;/a&gt;">
<script type="text/javascript">
<!--
function toggle_infmessages()
{
        allDivs=document.getElementsByTagName("div");
        for (var i = 0 ; i < allDivs.length ; i++ )
        {
                if (allDivs[i].className == "infmessage")
                {
                        allDivs[i].style.display=(allDivs[i].style.display == 'none' | allDivs[i].style.display == '') ? 'block' : 'none';
                }
        }
}
-->
</script>
</head>
<body>
<h1>Debian Bug report logs - 
<a href="mailto:854442@bugs.debian.org">#854442</a><br>
XXE vulnerability in python-openpyxl</h1>
<div class="versiongraph"><a href="version.cgi?found=openpyxl%2F2.3.0-2;fixed=openpyxl%2F2.3.0-3;package=python-openpyxl;collapse=1;absolute=0;info=1"><img alt="version graph" src="version.cgi?collapse=1;absolute=0;width=2;found=openpyxl%2F2.3.0-2;fixed=openpyxl%2F2.3.0-3;package=python-openpyxl;height=2"></a></div>
<div class="pkginfo">
  <p>Package:
     <a class="submitter" href="pkgreport.cgi?package=python-openpyxl">python-openpyxl</a>;
Maintainer for <a href="pkgreport.cgi?package=python-openpyxl">python-openpyxl</a> is <a href="pkgreport.cgi?maint=team%40neuro.debian.net">NeuroDebian Team &lt;team@neuro.debian.net&gt;</a>; Source for <a href="pkgreport.cgi?package=python-openpyxl">python-openpyxl</a> is <a href="pkgreport.cgi?src=openpyxl">src:openpyxl</a> (<a href="https://tracker.debian.org/pkg/openpyxl">PTS</a>, <a href="https://buildd.debian.org/openpyxl">buildd</a>, <a href="https://qa.debian.org/popcon.php?package=openpyxl">popcon</a>). </p>

</div>

<div class="buginfo">
  <p>Reported by: <a href="pkgreport.cgi?submitter=marcin.ulikowski%40f-secure.com">&quot;Ulikowski, Marcin&quot; &lt;marcin.ulikowski@f-secure.com&gt;</a></p>
  <p>Date: Tue,  7 Feb 2017 09:36:02 UTC</p>

<p>Severity: important</p>
<p>Tags: security</p>

<p>Found in version openpyxl/2.3.0-2</p>
<p>Fixed in version openpyxl/2.3.0-3</p>

<p><strong>Done:</strong> Yaroslav Halchenko &lt;debian@onerussian.com&gt;</p>

<p>Bug is archived. No further changes may be made.<p><p>Forwarded to <a href="https://bitbucket.org/openpyxl/openpyxl/issues/749">https://bitbucket.org/openpyxl/openpyxl/issues/749</a></p>
</div>

<p><a href="javascript:toggle_infmessages();">Toggle useless messages</a></p><div class="msgreceived"><p>View this report as an <a href="bugreport.cgi?bug=854442;mbox=yes">mbox folder</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;mboxstatus=yes">status mbox</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;mboxmaint=yes">maintainer mbox</a></p></div>

<div class="infmessage"><hr><p>
<a name="1"></a>
<!-- request_addr: debian-bugs-dist@lists.debian.org, NeuroDebian Team &lt;team@neuro.debian.net&gt; -->
<!-- time:1486460164 -->
<strong>Report forwarded</strong>
to <code>debian-bugs-dist@lists.debian.org, NeuroDebian Team &lt;team@neuro.debian.net&gt;</code>:<br>
<code>Bug#854442</code>; Package <code>python-openpyxl</code>.
 (Tue, 07 Feb 2017 09:36:04 GMT) (<a href="bugreport.cgi?bug=854442;msg=2">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=2">mbox</a>, <a href="#1">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="3"></a>
<!-- request_addr: &quot;Ulikowski, Marcin&quot; &lt;marcin.ulikowski@f-secure.com&gt; -->
<!-- time:1486460164 -->
<strong>Acknowledgement sent</strong>
to <code>&quot;Ulikowski, Marcin&quot; &lt;marcin.ulikowski@f-secure.com&gt;</code>:<br>
New Bug report received and forwarded.  Copy sent to <code>NeuroDebian Team &lt;team@neuro.debian.net&gt;</code>.<p>
<P>

Your message had a Version: pseudo-header with an invalid package
version:
<P>

&lt;= 2.3.5
<P>

please either use found or fixed to the control server with a correct
version, or reply to this report indicating the correct version so the
maintainer (or someone else) can correct it for you.
<P>

<p>

 (Tue, 07 Feb 2017 09:36:04 GMT) (<a href="bugreport.cgi?bug=854442;msg=4">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=4">mbox</a>, <a href="#3">link</a>).</p></p></div>

<hr><p class="msgreceived"><a name="5"></a><a name="msg5"></a><a href="#5">Message #5</a> received at submit@bugs.debian.org (<a href="bugreport.cgi?bug=854442;msg=5">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=5">mbox</a>, <a href="mailto:854442@bugs.debian.org?subject=Re%3A%20XXE%20vulnerability%20in%20python-openpyxl&amp;References=%3Cf6817a21fcc5489f84abdbdb2e990901%40helex02.FI.F-Secure.com%3E&amp;body=On%20Tue%2C%207%20Feb%202017%2009%3A27%3A51%20%2B0000%20%22Ulikowski%2C%20Marcin%22%20%3Cmarcin.ulikowski%40f-secure.com%3E%20wrote%3A%0A%3E%20Package%3A%20python-openpyxl%0A%3E%20Version%3A%20%3C%3D%202.3.5%0A%3E%20%0A%3E%20Openpyxl%20is%20vulnerable%20to%20XXE%20which%20allows%20reading%20local%20files%20and%20DoS%20an%20application.%20Openpyxl%20uses%20lxml%20which%20by%20default%20does%20resolve%20external%20entities%20and%20thus%20causes%20this%20vulnerability.%20This%20issue%20has%20been%20already%20reported%20to%20Openpyxl%20developers%20and%20was%20fixed%20about%20two%20weeks%20ago.%0A%3E%20%0A%3E%20https%3A%2F%2Fbitbucket.org%2Fopenpyxl%2Fopenpyxl%2Fcommits%2F3b4905f428e1%0A%3E%20%0A%3E%20I%27m%20attaching%20PoC%20code%20%28xxe-poc.zip%29%20which%20demonstrates%20this%20vulnerability.%20Script%20pyxl.py%20simulates%20a%20vulnerable%20application%20and%20takes%20Excel%20file%20as%20first%20argument.%20File%20blank_passwd.xlsx%20contains%20XXE%20payload%20which%20should%20read%20and%20store%20the%20contents%20of%20%2Fetc%2Fpasswd.%0A%3E%20%0A%3E%20--%20%0A%3E%20Marcin%20Ulikowski%0A%3E%20Senior%20Security%20Consultant%20%7C%20F-Secure%20CSS%0A%3E%20%0A&amp;In-Reply-To=%3Cf6817a21fcc5489f84abdbdb2e990901%40helex02.FI.F-Secure.com%3E">reply</a>):</p>
<div class="headers">
<img src="/cgi-bin/libravatar.cgi?email=marcin.ulikowski%40f-secure.com" alt="">
<div class="header"><span class="headerfield">From:</span> &quot;Ulikowski, Marcin&quot; &lt;marcin.ulikowski@f-secure.com&gt;</div>
<div class="header"><span class="headerfield">To:</span> &quot;submit@bugs.debian.org&quot; &lt;submit@bugs.debian.org&gt;</div>
<div class="header"><span class="headerfield">Subject:</span> XXE vulnerability in python-openpyxl</div>
<div class="header"><span class="headerfield">Date:</span> Tue, 7 Feb 2017 09:27:51 +0000</div>
</div>
<pre class="mime">[<a href="bugreport.cgi?att=0;bug=854442;msg=5">Message part 1</a> (text/plain, inline)]</pre>
<pre class="message">Package: python-openpyxl
Version: &lt;= 2.3.5

Openpyxl is vulnerable to XXE which allows reading local files and DoS an application. Openpyxl uses lxml which by default does resolve external entities and thus causes this vulnerability. This issue has been already reported to Openpyxl developers and was fixed about two weeks ago.

<a href="https://bitbucket.org/openpyxl/openpyxl/commits/3b4905f428e1">https://bitbucket.org/openpyxl/openpyxl/commits/3b4905f428e1</a>

I&#39;m attaching PoC code (xxe-poc.zip) which demonstrates this vulnerability. Script pyxl.py simulates a vulnerable application and takes Excel file as first argument. File blank_passwd.xlsx contains XXE payload which should read and store the contents of /etc/passwd.

-- 
Marcin Ulikowski
Senior Security Consultant | F-Secure CSS

</pre>
<pre class="mime">[<a href="bugreport.cgi?att=1;bug=854442;filename=xxe-poc.zip;msg=5">xxe-poc.zip</a> (application/x-zip-compressed, attachment)]</pre>

<div class="msgreceived"><hr><p>
<a name="6"></a>
<!-- command:tag -->
<!-- requester: Sebastien Delafond &lt;seb@debian.org&gt; -->
<!-- request_addr: control@bugs.debian.org -->
<!-- time:1486460704 -->
<!-- new_data:
$new_data = {
              &#39;keywords&#39; =&gt; &#39;security&#39;
            };
-->
<!-- old_data:
$old_data = {
              &#39;keywords&#39; =&gt; &#39;&#39;
            };
-->
<strong>Added tag(s) security.</strong>
Request was from <code>Sebastien Delafond &lt;seb@debian.org&gt;</code>
to <code>control@bugs.debian.org</code>.
 (Tue, 07 Feb 2017 09:45:04 GMT) (<a href="bugreport.cgi?bug=854442;msg=7">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=7">mbox</a>, <a href="#6">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="8"></a>
<!-- request_addr: debian-bugs-dist@lists.debian.org, NeuroDebian Team &lt;team@neuro.debian.net&gt; -->
<!-- time:1486478523 -->
<strong>Information forwarded</strong>
to <code>debian-bugs-dist@lists.debian.org, NeuroDebian Team &lt;team@neuro.debian.net&gt;</code>:<br>
<code>Bug#854442</code>; Package <code>python-openpyxl</code>.
 (Tue, 07 Feb 2017 14:42:03 GMT) (<a href="bugreport.cgi?bug=854442;msg=9">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=9">mbox</a>, <a href="#8">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="10"></a>
<!-- request_addr: Yaroslav Halchenko &lt;debian@onerussian.com&gt; -->
<!-- time:1486478523 -->
<strong>Acknowledgement sent</strong>
to <code>Yaroslav Halchenko &lt;debian@onerussian.com&gt;</code>:<br>
Extra info received and forwarded to list.  Copy sent to <code>NeuroDebian Team &lt;team@neuro.debian.net&gt;</code>.
 (Tue, 07 Feb 2017 14:42:03 GMT) (<a href="bugreport.cgi?bug=854442;msg=11">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=11">mbox</a>, <a href="#10">link</a>).</p></p></div>

<hr><p class="msgreceived"><a name="12"></a><a name="msg12"></a><a href="#12">Message #12</a> received at submit@bugs.debian.org (<a href="bugreport.cgi?bug=854442;msg=12">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=12">mbox</a>, <a href="mailto:854442@bugs.debian.org?subject=Re%3A%20Bug%23854442%3A%20XXE%20vulnerability%20in%20python-openpyxl&amp;In-Reply-To=%3C20170207144043.uhpgudj2lhdfvc6u%40hopa.kiewit.dartmouth.edu%3E&amp;body=On%20Tue%2C%207%20Feb%202017%2009%3A40%3A43%20-0500%20Yaroslav%20Halchenko%20%3Cdebian%40onerussian.com%3E%20wrote%3A%0A%3E%20thanks%20for%20the%20very%20detailed%20report%21%21%21%20I%20have%20adopted%20that%20patch%20for%20our%0A%3E%20now%20dated%20version%20of%20openpyxl%20%20--%20upload%20is%20coming%20shortly%0A%3E%20%0A%3E%20On%20Tue%2C%2007%20Feb%202017%2C%20Ulikowski%2C%20Marcin%20wrote%3A%0A%3E%20%0A%3E%20%3E%20Package%3A%20python-openpyxl%0A%3E%20%3E%20Version%3A%20%3C%3D%202.3.5%0A%3E%20%0A%3E%20%3E%20Openpyxl%20is%20vulnerable%20to%20XXE%20which%20allows%20reading%20local%20files%20and%20DoS%20an%20application.%20Openpyxl%20uses%20lxml%20which%20by%20default%20does%20resolve%20external%20entities%20and%20thus%20causes%20this%20vulnerability.%20This%20issue%20has%20been%20already%20reported%20to%20Openpyxl%20developers%20and%20was%20fixed%20about%20two%20weeks%20ago.%0A%3E%20%0A%3E%20%3E%20https%3A%2F%2Fbitbucket.org%2Fopenpyxl%2Fopenpyxl%2Fcommits%2F3b4905f428e1%0A%3E%20%0A%3E%20%3E%20I%27m%20attaching%20PoC%20code%20%28xxe-poc.zip%29%20which%20demonstrates%20this%20vulnerability.%20Script%20pyxl.py%20simulates%20a%20vulnerable%20application%20and%20takes%20Excel%20file%20as%20first%20argument.%20File%20blank_passwd.xlsx%20contains%20XXE%20payload%20which%20should%20read%20and%20store%20the%20contents%20of%20%2Fetc%2Fpasswd.%0A%3E%20--%20%0A%3E%20Yaroslav%20O.%20Halchenko%0A%3E%20Center%20for%20Open%20Neuroscience%20%20%20%20%20http%3A%2F%2Fcenterforopenneuroscience.org%0A%3E%20Dartmouth%20College%2C%20419%20Moore%20Hall%2C%20Hinman%20Box%206207%2C%20Hanover%2C%20NH%2003755%0A%3E%20Phone%3A%20%2B1%20%28603%29%20646-9834%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Fax%3A%20%2B1%20%28603%29%20646-1419%0A%3E%20WWW%3A%20%20%20http%3A%2F%2Fwww.linkedin.com%2Fin%2Fyarik%20%20%20%20%20%20%20%20%0A&amp;References=%3Cf6817a21fcc5489f84abdbdb2e990901%40helex02.FI.F-Secure.com%3E%0A%20%3C20170207144043.uhpgudj2lhdfvc6u%40hopa.kiewit.dartmouth.edu%3E">reply</a>):</p>
<div class="headers">
<img src="/cgi-bin/libravatar.cgi?email=debian%40onerussian.com" alt="">
<div class="header"><span class="headerfield">From:</span> Yaroslav Halchenko &lt;debian@onerussian.com&gt;</div>
<div class="header"><span class="headerfield">To:</span> &quot;Ulikowski, Marcin&quot; &lt;marcin.ulikowski@f-secure.com&gt;</div>
<div class="header"><span class="headerfield">Cc:</span> &quot;submit@bugs.debian.org&quot; &lt;submit@bugs.debian.org&gt;</div>
<div class="header"><span class="headerfield">Subject:</span> Re: Bug#854442: XXE vulnerability in python-openpyxl</div>
<div class="header"><span class="headerfield">Date:</span> Tue, 7 Feb 2017 09:40:43 -0500</div>
</div>
<pre class="mime">[<a href="bugreport.cgi?att=0;bug=854442;msg=12">Message part 1</a> (text/plain, inline)]</pre>
<pre class="message">thanks for the very detailed report!!! I have adopted that patch for our
now dated version of openpyxl  -- upload is coming shortly

On Tue, 07 Feb 2017, Ulikowski, Marcin wrote:

&gt; Package: python-openpyxl
&gt; Version: &lt;= 2.3.5

&gt; Openpyxl is vulnerable to XXE which allows reading local files and DoS an application. Openpyxl uses lxml which by default does resolve external entities and thus causes this vulnerability. This issue has been already reported to Openpyxl developers and was fixed about two weeks ago.

&gt; <a href="https://bitbucket.org/openpyxl/openpyxl/commits/3b4905f428e1">https://bitbucket.org/openpyxl/openpyxl/commits/3b4905f428e1</a>

&gt; I&#39;m attaching PoC code (xxe-poc.zip) which demonstrates this vulnerability. Script pyxl.py simulates a vulnerable application and takes Excel file as first argument. File blank_passwd.xlsx contains XXE payload which should read and store the contents of /etc/passwd.
-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     <a href="http://centerforopenneuroscience.org">http://centerforopenneuroscience.org</a>
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   <a href="http://www.linkedin.com/in/yarik">http://www.linkedin.com/in/yarik</a>        
</pre>
<pre class="mime">[<a href="bugreport.cgi?att=1;bug=854442;filename=signature.asc;msg=12">signature.asc</a> (application/pgp-signature, inline)]</pre>

<div class="infmessage"><hr><p>
<a name="13"></a>
<!-- request_addr: debian-bugs-dist@lists.debian.org, NeuroDebian Team &lt;team@neuro.debian.net&gt; -->
<!-- time:1486479063 -->
<strong>Information forwarded</strong>
to <code>debian-bugs-dist@lists.debian.org, NeuroDebian Team &lt;team@neuro.debian.net&gt;</code>:<br>
<code>Bug#854442</code>; Package <code>python-openpyxl</code>.
 (Tue, 07 Feb 2017 14:51:03 GMT) (<a href="bugreport.cgi?bug=854442;msg=14">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=14">mbox</a>, <a href="#13">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="15"></a>
<!-- request_addr: Yaroslav Halchenko &lt;debian@onerussian.com&gt; -->
<!-- time:1486479063 -->
<strong>Acknowledgement sent</strong>
to <code>Yaroslav Halchenko &lt;debian@onerussian.com&gt;</code>:<br>
Extra info received and forwarded to list.  Copy sent to <code>NeuroDebian Team &lt;team@neuro.debian.net&gt;</code>.
 (Tue, 07 Feb 2017 14:51:03 GMT) (<a href="bugreport.cgi?bug=854442;msg=16">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=16">mbox</a>, <a href="#15">link</a>).</p></p></div>

<hr><p class="msgreceived"><a name="17"></a><a name="msg17"></a><a href="#17">Message #17</a> received at 854442@bugs.debian.org (<a href="bugreport.cgi?bug=854442;msg=17">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=17">mbox</a>, <a href="mailto:854442@bugs.debian.org?subject=Re%3A%20Bug%23854442%3A%20XXE%20vulnerability%20in%20python-openpyxl&amp;References=%3Cf6817a21fcc5489f84abdbdb2e990901%40helex02.FI.F-Secure.com%3E%0A%20%3C20170207144043.uhpgudj2lhdfvc6u%40hopa.kiewit.dartmouth.edu%3E%0A%20%3C20170207144848.lged6ewu7deql3tx%40hopa.kiewit.dartmouth.edu%3E&amp;body=On%20Tue%2C%207%20Feb%202017%2009%3A48%3A48%20-0500%20Yaroslav%20Halchenko%20%3Cdebian%40onerussian.com%3E%20wrote%3A%0A%3E%20%0A%3E%20On%20Tue%2C%2007%20Feb%202017%2C%20Yaroslav%20Halchenko%20wrote%3A%0A%3E%20%0A%3E%20%3E%20thanks%20for%20the%20very%20detailed%20report%21%21%21%20I%20have%20adopted%20that%20patch%20for%20our%0A%3E%20%3E%20now%20dated%20version%20of%20openpyxl%20%20--%20upload%20is%20coming%20shortly%0A%3E%20%0A%3E%20unfortunately%20a%20blind%20adaptation%20of%20the%20patch%20wasn%27t%20sufficient%2C%20since%0A%3E%20running%20your%20PoC%20code%20results%20in%0A%3E%20%0A%3E%20%24%3E%20python%20pyxl.py%20blank_passwd.xlsx%20%20%20%20%20%20%20%20%20%20%0A%3E%20Traceback%20%28most%20recent%20call%20last%29%3A%0A%3E%20%20%20File%20%22pyxl.py%22%2C%20line%205%2C%20in%20%3Cmodule%3E%0A%3E%20%20%20%20%20wb%20%3D%20load_workbook%28filename%20%3D%20sys.argv%5B1%5D%29%0A%3E%20%20%20File%20%22%2Fusr%2Flib%2Fpython2.7%2Fdist-packages%2Fopenpyxl%2Freader%2Fexcel.py%22%2C%20line%20179%2C%20in%20load_workbook%0A%3E%20%20%20%20%20wb.properties%20%3D%20read_properties%28archive.read%28ARC_CORE%29%29%0A%3E%20%20%20File%20%22%2Fusr%2Flib%2Fpython2.7%2Fdist-packages%2Fopenpyxl%2Fworkbook%2Fproperties.py%22%2C%20line%20122%2C%20in%20read_properties%0A%3E%20%20%20%20%20tag%20%3D%20localname%28node%29%0A%3E%20%20%20File%20%22%2Fusr%2Flib%2Fpython2.7%2Fdist-packages%2Fopenpyxl%2Fxml%2Ffunctions.py%22%2C%20line%20122%2C%20in%20localname%0A%3E%20%20%20%20%20m%20%3D%20NS_REGEX.match%28node.tag%29%0A%3E%20TypeError%3A%20expected%20string%20or%20buffer%0A%3E%20%0A%3E%20%0A%3E%20while%20most%20recent%20release%202.4.2%20works%20correctly...%20before%20I%20dive%20into%20it%20--%20any%0A%3E%20clues%20what%20other%20changes%20should%20accompany%20the%20fix%3F%20%20I%20am%20attaching%20my%20adapted%0A%3E%20patch%0A%3E%20%0A%3E%20--%20%0A%3E%20Yaroslav%20O.%20Halchenko%0A%3E%20Center%20for%20Open%20Neuroscience%20%20%20%20%20http%3A%2F%2Fcenterforopenneuroscience.org%0A%3E%20Dartmouth%20College%2C%20419%20Moore%20Hall%2C%20Hinman%20Box%206207%2C%20Hanover%2C%20NH%2003755%0A%3E%20Phone%3A%20%2B1%20%28603%29%20646-9834%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Fax%3A%20%2B1%20%28603%29%20646-1419%0A%3E%20WWW%3A%20%20%20http%3A%2F%2Fwww.linkedin.com%2Fin%2Fyarik%20%20%20%20%20%20%20%20%0A&amp;In-Reply-To=%3C20170207144848.lged6ewu7deql3tx%40hopa.kiewit.dartmouth.edu%3E">reply</a>):</p>
<div class="headers">
<img src="/cgi-bin/libravatar.cgi?email=debian%40onerussian.com" alt="">
<div class="header"><span class="headerfield">From:</span> Yaroslav Halchenko &lt;debian@onerussian.com&gt;</div>
<div class="header"><span class="headerfield">To:</span> &quot;Ulikowski, Marcin&quot; &lt;marcin.ulikowski@f-secure.com&gt;</div>
<div class="header"><span class="headerfield">Cc:</span> 854442@bugs.debian.org</div>
<div class="header"><span class="headerfield">Subject:</span> Re: Bug#854442: XXE vulnerability in python-openpyxl</div>
<div class="header"><span class="headerfield">Date:</span> Tue, 7 Feb 2017 09:48:48 -0500</div>
</div>
<pre class="mime">[<a href="bugreport.cgi?att=0;bug=854442;msg=17">Message part 1</a> (text/plain, inline)]</pre>
<pre class="message">
On Tue, 07 Feb 2017, Yaroslav Halchenko wrote:

&gt; thanks for the very detailed report!!! I have adopted that patch for our
&gt; now dated version of openpyxl  -- upload is coming shortly

unfortunately a blind adaptation of the patch wasn&#39;t sufficient, since
running your PoC code results in

$&gt; python pyxl.py blank_passwd.xlsx          
Traceback (most recent call last):
  File &quot;pyxl.py&quot;, line 5, in &lt;module&gt;
    wb = load_workbook(filename = sys.argv[1])
  File &quot;/usr/lib/python2.7/dist-packages/openpyxl/reader/excel.py&quot;, line 179, in load_workbook
    wb.properties = read_properties(archive.read(ARC_CORE))
  File &quot;/usr/lib/python2.7/dist-packages/openpyxl/workbook/properties.py&quot;, line 122, in read_properties
    tag = localname(node)
  File &quot;/usr/lib/python2.7/dist-packages/openpyxl/xml/functions.py&quot;, line 122, in localname
    m = NS_REGEX.match(node.tag)
TypeError: expected string or buffer


while most recent release 2.4.2 works correctly... before I dive into it -- any
clues what other changes should accompany the fix?  I am attaching my adapted
patch

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     <a href="http://centerforopenneuroscience.org">http://centerforopenneuroscience.org</a>
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   <a href="http://www.linkedin.com/in/yarik">http://www.linkedin.com/in/yarik</a>        
</pre>
<pre class="mime">[<a href="bugreport.cgi?att=1;bug=854442;filename=up_no_lxml;msg=17">up_no_lxml</a> (text/plain, attachment)]</pre>
<pre class="mime">[<a href="bugreport.cgi?att=2;bug=854442;filename=signature.asc;msg=17">signature.asc</a> (application/pgp-signature, inline)]</pre>

<div class="infmessage"><hr><p>
<a name="18"></a>
<!-- request_addr: debian-bugs-dist@lists.debian.org, NeuroDebian Team &lt;team@neuro.debian.net&gt; -->
<!-- time:1486593185 -->
<strong>Information forwarded</strong>
to <code>debian-bugs-dist@lists.debian.org, NeuroDebian Team &lt;team@neuro.debian.net&gt;</code>:<br>
<code>Bug#854442</code>; Package <code>python-openpyxl</code>.
 (Wed, 08 Feb 2017 22:33:05 GMT) (<a href="bugreport.cgi?bug=854442;msg=19">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=19">mbox</a>, <a href="#18">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="20"></a>
<!-- request_addr: Markus Koschany &lt;apo@debian.org&gt; -->
<!-- time:1486593185 -->
<strong>Acknowledgement sent</strong>
to <code>Markus Koschany &lt;apo@debian.org&gt;</code>:<br>
Extra info received and forwarded to list.  Copy sent to <code>NeuroDebian Team &lt;team@neuro.debian.net&gt;</code>.
 (Wed, 08 Feb 2017 22:33:05 GMT) (<a href="bugreport.cgi?bug=854442;msg=21">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=21">mbox</a>, <a href="#20">link</a>).</p></p></div>

<hr><p class="msgreceived"><a name="22"></a><a name="msg22"></a><a href="#22">Message #22</a> received at 854442@bugs.debian.org (<a href="bugreport.cgi?bug=854442;msg=22">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=22">mbox</a>, <a href="mailto:854442@bugs.debian.org?subject=Re%3A%20XXE%20vulnerability%20in%20python-openpyxl&amp;In-Reply-To=%3C0b7a41d3-c19e-32a4-af32-7e883cb31b76%40debian.org%3E&amp;References=%3Cf6817a21fcc5489f84abdbdb2e990901%40helex02.FI.F-Secure.com%3E%0A%20%3Cf6817a21fcc5489f84abdbdb2e990901%40helex02.FI.F-Secure.com%3E%0A%20%3C0b7a41d3-c19e-32a4-af32-7e883cb31b76%40debian.org%3E&amp;body=On%20Wed%2C%208%20Feb%202017%2023%3A30%3A26%20%2B0100%20Markus%20Koschany%20%3Capo%40debian.org%3E%20wrote%3A%0A%3E%20Hi%2C%0A%3E%20%0A%3E%20I%20am%20currently%20investigating%20if%20the%20versions%20of%20openpyxl%20in%20Wheezy%20and%0A%3E%20Jessie%20are%20vulnerable.%20Apparently%20support%20for%20lxml%20was%20first%20introduced%0A%3E%20in%20version%201.8.%20Wheezy%20and%20Jessie%20ship%20older%20versions%20though.%0A%3E%20%0A%3E%20Is%20there%20another%20attack%20vector%20or%20can%20we%20assume%20that%20all%20versions%0A%3E%20without%20lxml%20support%20are%20not%20affected%3F%0A%3E%20%0A%3E%20Regards%2C%0A%3E%20%0A%3E%20Markus%0A%3E%20%0A">reply</a>):</p>
<div class="headers">
<img src="/cgi-bin/libravatar.cgi?email=apo%40debian.org" alt="">
<div class="header"><span class="headerfield">From:</span> Markus Koschany &lt;apo@debian.org&gt;</div>
<div class="header"><span class="headerfield">To:</span> marcin.ulikowski@f-secure.com, debian@onerussian.com</div>
<div class="header"><span class="headerfield">Cc:</span> 854442@bugs.debian.org</div>
<div class="header"><span class="headerfield">Subject:</span> Re: XXE vulnerability in python-openpyxl</div>
<div class="header"><span class="headerfield">Date:</span> Wed, 8 Feb 2017 23:30:26 +0100</div>
</div>
<pre class="mime">[<a href="bugreport.cgi?att=0;bug=854442;msg=22">Message part 1</a> (text/plain, inline)]</pre>
<pre class="message">Hi,

I am currently investigating if the versions of openpyxl in Wheezy and
Jessie are vulnerable. Apparently support for lxml was first introduced
in version 1.8. Wheezy and Jessie ship older versions though.

Is there another attack vector or can we assume that all versions
without lxml support are not affected?

Regards,

Markus

</pre>
<pre class="mime">[<a href="bugreport.cgi?att=1;bug=854442;filename=signature.asc;msg=22">signature.asc</a> (application/pgp-signature, attachment)]</pre>

<div class="msgreceived"><hr><p>
<a name="23"></a>
<!-- command:forwarded -->
<!-- requester: Salvatore Bonaccorso &lt;carnil@debian.org&gt; -->
<!-- request_addr: control@bugs.debian.org -->
<!-- time:1487164863 -->
<!-- new_data:
$new_data = {
              &#39;forwarded&#39; =&gt; &#39;<a href="https://bitbucket.org/openpyxl/openpyxl/issues/749">https://bitbucket.org/openpyxl/openpyxl/issues/749</a>&#39;
            };
-->
<!-- old_data:
$old_data = {
              &#39;forwarded&#39; =&gt; &#39;&#39;
            };
-->
<strong>Set Bug forwarded-to-address to &#39;<a href="https://bitbucket.org/openpyxl/openpyxl/issues/749">https://bitbucket.org/openpyxl/openpyxl/issues/749</a>&#39;.</strong>
Request was from <code>Salvatore Bonaccorso &lt;carnil@debian.org&gt;</code>
to <code>control@bugs.debian.org</code>.
 (Wed, 15 Feb 2017 13:21:03 GMT) (<a href="bugreport.cgi?bug=854442;msg=24">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=24">mbox</a>, <a href="#23">link</a>).</p></p></div>

<div class="msgreceived"><hr><p>
<a name="25"></a>
<!-- request_addr: Yaroslav Halchenko &lt;debian@onerussian.com&gt; -->
<!-- time:1487170443 -->
<strong>Reply sent</strong>
to <code>Yaroslav Halchenko &lt;debian@onerussian.com&gt;</code>:<br>
You have taken responsibility.
 (Wed, 15 Feb 2017 14:54:03 GMT) (<a href="bugreport.cgi?bug=854442;msg=26">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=26">mbox</a>, <a href="#25">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="27"></a>
<!-- request_addr: &quot;Ulikowski, Marcin&quot; &lt;marcin.ulikowski@f-secure.com&gt; -->
<!-- time:1487170443 -->
<strong>Notification sent</strong>
to <code>&quot;Ulikowski, Marcin&quot; &lt;marcin.ulikowski@f-secure.com&gt;</code>:<br>
Bug acknowledged by developer.
 (Wed, 15 Feb 2017 14:54:03 GMT) (<a href="bugreport.cgi?bug=854442;msg=28">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=28">mbox</a>, <a href="#27">link</a>).</p></p></div>

<hr><p class="msgreceived"><a name="29"></a><a name="msg29"></a><a href="#29">Message #29</a> received at 854442-close@bugs.debian.org (<a href="bugreport.cgi?bug=854442;msg=29">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=29">mbox</a>, <a href="mailto:854442@bugs.debian.org?References=%3CE1ce0vB-000CYL-Ku%40fasolo.debian.org%3E&amp;body=On%20Wed%2C%2015%20Feb%202017%2014%3A51%3A05%20%2B0000%20Yaroslav%20Halchenko%20%3Cdebian%40onerussian.com%3E%20wrote%3A%0A%3E%20Source%3A%20openpyxl%0A%3E%20Source-Version%3A%202.3.0-3%0A%3E%20%0A%3E%20We%20believe%20that%20the%20bug%20you%20reported%20is%20fixed%20in%20the%20latest%20version%20of%0A%3E%20openpyxl%2C%20which%20is%20due%20to%20be%20installed%20in%20the%20Debian%20FTP%20archive.%0A%3E%20%0A%3E%20A%20summary%20of%20the%20changes%20between%20this%20version%20and%20the%20previous%20one%20is%0A%3E%20attached.%0A%3E%20%0A%3E%20Thank%20you%20for%20reporting%20the%20bug%2C%20which%20will%20now%20be%20closed.%20%20If%20you%0A%3E%20have%20further%20comments%20please%20address%20them%20to%20854442%40bugs.debian.org%2C%0A%3E%20and%20the%20maintainer%20will%20reopen%20the%20bug%20report%20if%20appropriate.%0A%3E%20%0A%3E%20Debian%20distribution%20maintenance%20software%0A%3E%20pp.%0A%3E%20Yaroslav%20Halchenko%20%3Cdebian%40onerussian.com%3E%20%28supplier%20of%20updated%20openpyxl%20package%29%0A%3E%20%0A%3E%20%28This%20message%20was%20generated%20automatically%20at%20their%20request%3B%20if%20you%0A%3E%20believe%20that%20there%20is%20a%20problem%20with%20it%20please%20contact%20the%20archive%0A%3E%20administrators%20by%20mailing%20ftpmaster%40ftp-master.debian.org%29%0A%3E%20%0A%3E%20%0A%3E%20-----BEGIN%20PGP%20SIGNED%20MESSAGE-----%0A%3E%20Hash%3A%20SHA256%0A%3E%20%0A%3E%20Format%3A%201.8%0A%3E%20Date%3A%20Tue%2C%2007%20Feb%202017%2009%3A37%3A53%20-0500%0A%3E%20Source%3A%20openpyxl%0A%3E%20Binary%3A%20python-openpyxl%20python3-openpyxl%0A%3E%20Architecture%3A%20source%20all%0A%3E%20Version%3A%202.3.0-3%0A%3E%20Distribution%3A%20unstable%0A%3E%20Urgency%3A%20medium%0A%3E%20Maintainer%3A%20NeuroDebian%20Team%20%3Cteam%40neuro.debian.net%3E%0A%3E%20Changed-By%3A%20Yaroslav%20Halchenko%20%3Cdebian%40onerussian.com%3E%0A%3E%20Description%3A%0A%3E%20%20python-openpyxl%20-%20module%20to%20read%2Fwrite%20OpenXML%20xlsx%2Fxlsm%20files%0A%3E%20%20python3-openpyxl%20-%20module%20to%20read%2Fwrite%20OpenXML%20xlsx%2Fxlsm%20files%0A%3E%20Closes%3A%20854442%0A%3E%20Changes%3A%0A%3E%20%20openpyxl%20%282.3.0-3%29%20unstable%3B%20urgency%3Dmedium%0A%3E%20%20.%0A%3E%20%20%20%20%2A%20Do%20not%20resolve%20entities%20with%20lxml%20to%20avoid%20XXE%20vulnerability%0A%3E%20%20%20%20%20%20-%20patch%20up_no_lxml%20%28Closes%3A%20%23854442%29%0A%3E%20Checksums-Sha1%3A%0A%3E%20%20dc13b62a63628849d12cedb7a0bd40e2f6d5c9ab%202323%20openpyxl_2.3.0-3.dsc%0A%3E%20%20b0e098d3b3350b1495d6cd5db134c3d7edf18ec2%205872%20openpyxl_2.3.0-3.debian.tar.xz%0A%3E%20%200161ac41c48b405fdd0f98ab172f18660a5ab159%206150%20openpyxl_2.3.0-3_amd64.buildinfo%0A%3E%20%20ffa78477c12fa677f707bc28a75f6b29a0549e58%20198944%20python-openpyxl_2.3.0-3_all.deb%0A%3E%20%207d7150f55b569d9b2fae8128546f63142d411098%20198146%20python3-openpyxl_2.3.0-3_all.deb%0A%3E%20Checksums-Sha256%3A%0A%3E%20%2077427e84ffe07c6b2f436c961a78bcc759aa20c09d8738b38dc60ea9fe902409%202323%20openpyxl_2.3.0-3.dsc%0A%3E%20%20c1d92e10479d1cf37cb0780f434d322ad800afb7ba98a5f918d0c3162be392b5%205872%20openpyxl_2.3.0-3.debian.tar.xz%0A%3E%20%20c238d76cf14de36dfd09f89052c93cf63953162d7dfaa6cfad184aeba1a8655f%206150%20openpyxl_2.3.0-3_amd64.buildinfo%0A%3E%20%2077885ecfdc15805aaa0e56d581956e10b5c64b38e96d66b7000ac256591ae2b4%20198944%20python-openpyxl_2.3.0-3_all.deb%0A%3E%20%205b16a2ed151da38c70bcf32f04f9f265dff473c5711bb29485da533e034ee62c%20198146%20python3-openpyxl_2.3.0-3_all.deb%0A%3E%20Files%3A%0A%3E%20%20f6ed85091c54389c0b2d9e1a083a0089%202323%20python%20optional%20openpyxl_2.3.0-3.dsc%0A%3E%20%20570a100f7341ede0c5af604a4aa234ea%205872%20python%20optional%20openpyxl_2.3.0-3.debian.tar.xz%0A%3E%20%20de327bba7b678f180b8bcebee74cd672%206150%20python%20optional%20openpyxl_2.3.0-3_amd64.buildinfo%0A&amp;In-Reply-To=%3CE1ce0vB-000CYL-Ku%40fasolo.debian.org%3E&amp;subject=Re%3A%20Bug%23854442%3A%20fixed%20in%20openpyxl%202.3.0-3">reply</a>):</p>
<div class="headers">
<img src="/cgi-bin/libravatar.cgi?email=debian%40onerussian.com" alt="">
<div class="header"><span class="headerfield">From:</span> Yaroslav Halchenko &lt;debian@onerussian.com&gt;</div>
<div class="header"><span class="headerfield">To:</span> 854442-close@bugs.debian.org</div>
<div class="header"><span class="headerfield">Subject:</span> Bug#854442: fixed in openpyxl 2.3.0-3</div>
<div class="header"><span class="headerfield">Date:</span> Wed, 15 Feb 2017 14:51:05 +0000</div>
</div>
<pre class="message">Source: openpyxl
Source-Version: 2.3.0-3

We believe that the bug you reported is fixed in the latest version of
openpyxl, which is due to be installed in the Debian FTP archive.

A summary of the changes between this version and the previous one is
attached.

Thank you for reporting the bug, which will now be closed.  If you
have further comments please address them to 854442@bugs.debian.org,
and the maintainer will reopen the bug report if appropriate.

Debian distribution maintenance software
pp.
Yaroslav Halchenko &lt;debian@onerussian.com&gt; (supplier of updated openpyxl package)

(This message was generated automatically at their request; if you
believe that there is a problem with it please contact the archive
administrators by mailing ftpmaster@ftp-master.debian.org)


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Format: 1.8
Date: Tue, 07 Feb 2017 09:37:53 -0500
Source: openpyxl
Binary: python-openpyxl python3-openpyxl
Architecture: source all
Version: 2.3.0-3
Distribution: unstable
Urgency: medium
Maintainer: NeuroDebian Team &lt;team@neuro.debian.net&gt;
Changed-By: Yaroslav Halchenko &lt;debian@onerussian.com&gt;
Description:
 python-openpyxl - module to read/write OpenXML xlsx/xlsm files
 python3-openpyxl - module to read/write OpenXML xlsx/xlsm files
Closes: <a href="bugreport.cgi?bug=854442">854442</a>
Changes:
 openpyxl (2.3.0-3) unstable; urgency=medium
 .
   * Do not resolve entities with lxml to avoid XXE vulnerability
     - patch up_no_lxml (Closes: #<a href="bugreport.cgi?bug=854442">854442</a>)
Checksums-Sha1:
 dc13b62a63628849d12cedb7a0bd40e2f6d5c9ab 2323 openpyxl_2.3.0-3.dsc
 b0e098d3b3350b1495d6cd5db134c3d7edf18ec2 5872 openpyxl_2.3.0-3.debian.tar.xz
 0161ac41c48b405fdd0f98ab172f18660a5ab159 6150 openpyxl_2.3.0-3_amd64.buildinfo
 ffa78477c12fa677f707bc28a75f6b29a0549e58 198944 python-openpyxl_2.3.0-3_all.deb
 7d7150f55b569d9b2fae8128546f63142d411098 198146 python3-openpyxl_2.3.0-3_all.deb
Checksums-Sha256:
 77427e84ffe07c6b2f436c961a78bcc759aa20c09d8738b38dc60ea9fe902409 2323 openpyxl_2.3.0-3.dsc
 c1d92e10479d1cf37cb0780f434d322ad800afb7ba98a5f918d0c3162be392b5 5872 openpyxl_2.3.0-3.debian.tar.xz
 c238d76cf14de36dfd09f89052c93cf63953162d7dfaa6cfad184aeba1a8655f 6150 openpyxl_2.3.0-3_amd64.buildinfo
 77885ecfdc15805aaa0e56d581956e10b5c64b38e96d66b7000ac256591ae2b4 198944 python-openpyxl_2.3.0-3_all.deb
 5b16a2ed151da38c70bcf32f04f9f265dff473c5711bb29485da533e034ee62c 198146 python3-openpyxl_2.3.0-3_all.deb
Files:
 f6ed85091c54389c0b2d9e1a083a0089 2323 python optional openpyxl_2.3.0-3.dsc
 570a100f7341ede0c5af604a4aa234ea 5872 python optional openpyxl_2.3.0-3.debian.tar.xz
 de327bba7b678f180b8bcebee74cd672 6150 python optional openpyxl_2.3.0-3_amd64.buildinfo
 7846059894566a1efd6e78fa95761d30 198944 python optional python-openpyxl_2.3.0-3_all.deb
 d45e53a0d6cc104ee1a08aa9f484bb7a 198146 python optional python3-openpyxl_2.3.0-3_all.deb

-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEExbkF8OjZ/ZZo/zZvot4jUGLaM/oFAlikX+UACgkQot4jUGLa
M/r4cQ/+K6KOQwoj9QwEcX4dn0Y/jDTdh3F/fesw9tLR+AscToJ2dTJXmvzCodTI
WubJHSuFFuLStzbHijK4248Y59Bj03Ae5f2koB2HkWFd5MH8efy9V4kBAFK0ibCj
FHBDXMW/sbVPRME8F9u8CmqxWtmPzP7fK4F6TVT9GG66x4p3yQzB/PS1RrTtj2MA
TdkdVeazmuZ2rJvl5MXrKFF1dPtyKCZD+fM4osO9XXHmHVGAemhQ1UlgmffZX14I
plbKifwX6Z8BDLzg6gOtEBcvc4vKjHi6fGMyIQbzLinZByB0LNolyn77zL45mVnA
gaov10d3TU/LCEfB7tgKADdTGzoitw36eocJz2uqNCTnG70+PG/tR1z07ege9LKZ
xHN5Q1StzylvflM6/L+yV5YlS9Xh74ztvo36LNMjYD/o9nI8u9Z7K43ACKL5nLqV
+EKAtcwNiOIK1gQE3OhJdcaypf79tCHwCz9qxIylUChnmbXChP591uDxHz4nuHuF
ESJH+kDJzrGIz39d5aAGSNFg99XOTWMvGW8pIW2qC7+sLug+KAD05PtbMDDb0lml
HE99laDaIp0J8MKOpPlsq/yYTeiGHlZY8k7a1YD4fkjMvDht7E7l5nz3EnjqSKRM
/MsLr5mfUCLG0Og3R3G6sUTQ9sTU2TMhFGRMqraXXPxmAsYwXrU=
=HUfI
-----END PGP SIGNATURE-----



</pre>

<div class="msgreceived"><hr><p>
<a name="30"></a>
<!-- command:found -->
<!-- requester: Salvatore Bonaccorso &lt;carnil@debian.org&gt; -->
<!-- request_addr: control@bugs.debian.org -->
<!-- time:1490897163 -->
<!-- new_data:
$new_data = {
              &#39;found_versions&#39; =&gt; [
                                    &#39;openpyxl/2.3.0-2&#39;
                                  ]
            };
-->
<!-- old_data:
$old_data = {
              &#39;found_versions&#39; =&gt; []
            };
-->
<strong>Marked as found in versions openpyxl/2.3.0-2.</strong>
Request was from <code>Salvatore Bonaccorso &lt;carnil@debian.org&gt;</code>
to <code>control@bugs.debian.org</code>.
 (Thu, 30 Mar 2017 18:06:03 GMT) (<a href="bugreport.cgi?bug=854442;msg=31">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=31">mbox</a>, <a href="#30">link</a>).</p></p></div>

<div class="msgreceived"><hr><p>
<a name="32"></a>
<!-- requester: Salvatore Bonaccorso &lt;carnil@debian.org&gt; -->
<!-- request_addr: control@bugs.debian.org -->
<!-- time:1490897164 -->
<strong>Severity set to &#39;important&#39; from &#39;normal&#39;</strong>
Request was from <code>Salvatore Bonaccorso &lt;carnil@debian.org&gt;</code>
to <code>control@bugs.debian.org</code>.
 (Thu, 30 Mar 2017 18:06:04 GMT) (<a href="bugreport.cgi?bug=854442;msg=33">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=33">mbox</a>, <a href="#32">link</a>).</p></p></div>

<div class="msgreceived"><hr><p>
<a name="34"></a>
<!-- command:archive -->
<!-- requester: Debbugs Internal Request &lt;owner@bugs.debian.org&gt; -->
<!-- request_addr: internal_control@bugs.debian.org -->
<!-- time:1493364422 -->
<!-- new_data:
$new_data = {};
-->
<!-- old_data:
$old_data = {};
-->
<strong>Bug archived.</strong>
Request was from <code>Debbugs Internal Request &lt;owner@bugs.debian.org&gt;</code>
to <code>internal_control@bugs.debian.org</code>.
 (Fri, 28 Apr 2017 07:27:02 GMT) (<a href="bugreport.cgi?bug=854442;msg=35">full text</a>, <a href="bugreport.cgi?bug=854442;mbox=yes;msg=35">mbox</a>, <a href="#34">link</a>).</p></p></div>

<hr>
<p class="msgreceived">Send a report that <a href="https://bugs.debian.org/cgi-bin/bugspam.cgi?bug=854442">this bug log contains spam</a>.</p>
<hr>
<ADDRESS>Debian bug tracking system administrator &lt;<A HREF="mailto:owner@bugs.debian.org">owner@bugs.debian.org</A>&gt;.
Last modified:
<!--timestamp-->Sat Oct 30 18:33:36 2021<!--end timestamp-->; 
Machine Name:
<!--machinename-->buxtehude<!--machinename-->
<P>
<A HREF="https://www.debian.org/Bugs/">Debian Bug tracking system</A>
</p>
<p>
  Debbugs is free software and licensed under the terms of the GNU
  Public License version 2. The current version can be obtained
  from <a href="https://bugs.debian.org/debbugs-source/">https://bugs.debian.org/debbugs-source/</a>.
</p>
<p>
Copyright © 1999 Darren O. Benham,
1997,2003 nCipher Corporation Ltd,
1994-97 Ian Jackson,
2005-2017 Don Armstrong, and many other contributors.
</p>
</ADDRESS>

</body>
</html>
