{
    "error": "HTTPSConnectionPool(host='blog.skullsec.com.br', port=443): Max retries exceeded with url: /CVE-2020-12262/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f52dae94400>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
}