{
    "error": "HTTPSConnectionPool(host='bugzilla.ubuntu.com', port=443): Max retries exceeded with url: /show_bug.cgi?id=12008 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f01d40a77f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
}