{
    "error": "HTTPConnectionPool(host='445544.44.ohost.de', port=80): Max retries exceeded with url: /worldlabburningboardadon2python-1.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7effc5bb48e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
}