{
    "error": "HTTPSConnectionPool(host='bugzilla.osafoundation.org', port=443): Max retries exceeded with url: /show_bug.cgi?id=11587 (Caused by SSLError(SSLError(\"bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])\")))"
}