{
    "osv": {
        "package": {
            "name": "python-django"
        },
        "published": "2013-09-11",
        "references": [
            {
                "type": "DSA",
                "url": "https://www.debian.org/security/2013/dsa-2755"
            }
        ]
    },
    "uvi": {
        "experimental": {
            "advisory_type": "DSA-2755-1",
            "other_identifiers": {
                "cve": [
                    "CVE-2013-4315"
                ]
            },
            "package_affected": [
                {
                    "distribution_affected": "squeeze",
                    "fixed in": "1.2.3-3+squeeze7"
                },
                {
                    "distribution_affected": "wheezy",
                    "fixed in": "1.4.5-1+deb7u3"
                },
                {
                    "distribution_affected": "sid",
                    "fixed in": "For the unstable distribution (sid), this problem will be fixed soon"
                }
            ],
            "package_name": "python-django",
            "processed_timestamp": "2021-07-18T03:08:53.364957Z",
            "uvi_script_name": "./www.debian.org-processing.py",
            "uvi_script_version": "0.0.5",
            "vulnerability_status": "yes"
        },
        "product_name": "Linux",
        "vendor_name": "Debian"
    }
}