{
    "error": "HTTPSConnectionPool(host='1.337.zone', port=443): Max retries exceeded with url: /2019/04/08/intelbras-iwr-3000n-any-version-dos-on-malformed-login-request/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8d186653a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
}